package model

import (
	"encoding/json"
	"fmt"
)

func InitModel(modelID int) *AutoGenerated {
	if modelID == 0 {
		panic("empty modelID")
	}
	return &AutoGenerated{
		Annotations: Annotations{
			[]OutSideList{
				{
					BuiltIn:    1,
					Datasource: "-- Grafana --",
					Enable:     true,
					Hide:       true,
					IconColor:  "rgba(0, 211, 255, 1)",
					Name:       "Annotations & Alerts",
					Type:       "dashboard",
				},
			},
		},
		Editable:      true,
		GnetID:        nil,
		GraphTooltip:  0,
		ID:            modelID, // changable
		Links:         []any{},
		Panels:        nil,
		Refresh:       "",
		SchemaVersion: 27,
		Style:         "dark",
		Tags:          []any{},
		Templating:    Templating{List: []any{}},
		Time: Time{
			From: "now-6h",
			To:   "now",
		},
		Timepicker: Timepicker{},
		Timezone:   "",
		Title:      "Alarm_Kafka",
		UID:        "iqlByAX4k",
		Version:    2,
	}
}

func InitModelByPassIn(modelData string) *AutoGenerated {
	var res = &AutoGenerated{}
	if err := json.Unmarshal([]byte(modelData), res); err != nil {
		fmt.Printf("InitModelByPassIn err:%s", err.Error())
		panic(err)
	}
	return res
}
